version: 2
# registries:
#   maven-github:
#     type: maven-repository
#     url: https://maven.pkg.github.com/octocat
#     username: octocat
#     password: ${{secrets.MY_ARTIFACTORY_PASSWORD}}
#   npm-npmjs:
#     type: npm-registry
#     url: https://registry.npmjs.org
#     username: octocat
#     password: ${{secrets.MY_NPM_PASSWORD}}
updates:
  # - package-ecosystem: gradle
  #   directory: /
  #   schedule:
  #     interval: monthly
  #   commit-message:
  #     prefix: gradle prod
  #     prefix-development: gradle dev      
  #     include: scope

  # - package-ecosystem: npm
  #   directory: /trunk/webapps/cxstudio-ui
  #   schedule:
  #     interval: monthly
  #   commit-message:
  #     prefix: npm prod
  #     prefix-development: npm dev
  #     include: scope

  - package-ecosystem: npm
    directory: /
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
      day: monday
      time: "13:30"
      timezone: America/New_York
    commit-message:
      prefix: npm prod
      prefix-development: npm dev
      include: scope